branches:
 except:
  - /appveyor/
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq xvfb libx11-dev $([ "$USE_XFT" = "no" ] || echo -n "libfreetype6-dev libxft-dev") $LIBPNG $LIBZ $LIBJPEG $([ "$WINDOW_MANAGER" = "kwin" ] && echo -n "kde-window-manager" || echo -n $WINDOW_MANAGER)
 - '[ "$USE_SYSTEM_PERL" = "1" ] && perlbrew off || true'
# optional, for tests
 - '[ "$WITH_TEST_POD" = "yes" ] && cpanm --quiet --notest Test::Pod || true'
 - Xvfb :123 &
 - export DISPLAY=:123
 - (sleep 10; $WINDOW_MANAGER) &
script:
 - perl Makefile.PL && env HARNESS_TIMER=1 make test
language: perl
matrix:
 include:
  - perl: "5.14"
    env: USE_SYSTEM_PERL=1 WINDOW_MANAGER=twm WITH_TEST_POD=no LIBPNG=libpng-dev LIBZ=libz-dev LIBJPEG=libjpeg-dev
  - perl: "5.20"
    env: WINDOW_MANAGER=twm
## t/fbox.t fails, not reproducible on a freebsd system
#  - perl: "5.18"
#    env: WINDOW_MANAGER=metacity LIBPNG=libpng-dev LIBZ=libz-dev LIBJPEG=libjpeg-dev
  - perl: "5.18"
    env: WINDOW_MANAGER=xfwm4 LIBPNG=libpng-dev LIBZ=libz-dev LIBJPEG=libjpeg-dev
  - perl: "5.16"
    env: WINDOW_MANAGER=fluxbox
  - perl: "5.14"
    env: WINDOW_MANAGER=sawfish LIBPNG=libpng-dev LIBZ=libz-dev LIBJPEG=libjpeg-dev
  - perl: "5.12"
    env: WINDOW_MANAGER=kwin
  - perl: "5.10"
    env: WINDOW_MANAGER=fvwm LIBPNG=libpng-dev LIBZ=libz-dev LIBJPEG=libjpeg-dev
  - perl: "5.8"
    env: WINDOW_MANAGER=twm USE_XFT=no
  - perl: "5.20"
    env: WINDOW_MANAGER=twm USE_XFT=no WITH_TEST_POD=yes
